### ISSUE TITLE
Move Configurate Output Out of /madminer directory

### ISSUE THREAD

**Issue by BenGalewsky** [scailfin/workflow-madminer#21]
# Problem
The `configurate` step writes the output into the same directory where the Madminer code lives. This is bad practice and causes security faults.

There may be outputs from other steps that do the same thing

# Approach
Create a scratch volume where these files are written

**Comment by Sinclert** [comment]
After a brief discussion over Zoom, we clarified why this goal is important (basically to allow files persistency across _Yadage_ / _REANA_ steps), and we agreed I will proposed a PR to address it.

**Comment by Sinclert** [comment]
PR addressing this issue: https://github.com/scailfin/workflow-madminer/pull/27
