### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by cranmer** [scailfin/workflow-madminer#4]
Documentation points to 
[tutorial] (https://github.com/johannbrehmer/madminer/blob/master/examples/tutorial/tutorial_1.ipynb) 

2 issues: 
 1. there is no tutorial directory inside examples anymore. 
 2. the main URL for Madminer is now https://github.com/diana-hep/madminer/

**Comment by cranmer** [comment]
I'm not sure if the new URL for the location of the repository is going to break some of the continuous integration tests.

**Comment by irinaespejo** [comment]
It's possible the CI breaks when trying to push a new docker image. We'll have to wait until the next release to fix it or we can make a dumb release to test it.

**Comment by johannbrehmer** [comment]
The tutorial got renamed some time ago to `tutorial_particle_physics` (to distinguish from the toy example).

**Comment by irinaespejo** [comment]
Looks like the CI didn't break in https://travis-ci.com/diana-hep/madminer
